### ISSUE TITLE
Code for email attachments remains in email body while using org-mu4e-compose-org-mode

### ISSUE THREAD

**Issue by shrysr** [jkitchin/scimax#180] opened 2018-03-05 18:27 UTC
I am using mu4e ver 1.0-alpha2 C on Antergos (Arch based Linux distribution) to manage my emails, via scimax. The issue I face is that the code snippet for file attachments being visible in the mail body when I use org-mu4e-compose-org-mode.

Normal text based mu4e-compose mode works fine. However, when I use the org-mu4e-compose-org-mode option for email formatting, and I use mml-attach-file for attachments, the code used to add attachments remains in the email body which is sent. 

Procedure:
1. Usually compose my email in org mode, then copy over to a mu4e-compose buffer, use M-x org-mu4e-compose-org-mode.  
2. Complete attachments using mml-attach-file.  
3. I hit C-c C-c in the Email header area for the email to be sent.   

Notes: 
- The attachments do get attached. I do not face this problem in the usual mu4e-compose mode. 

![deepinscreenshot_select-area_20180305110407](https://user-images.githubusercontent.com/11930484/36992347-a15aef00-2078-11e8-9b2d-b343d22c6922.png)

**Comment by jkitchin** [comment] 2018-03-06 02:31
I have not been able to reproduce this.

**Comment by kjschanney** [comment] 2018-03-29 23:35
Hi,
I am having the exact same issue.
Although I am not using scimax, I am using spacemacs on arch linux. I am attaching the files from dired as explained [here](http://www.djcbsoftware.nl/code/mu/mu4e/Attaching-files-with-dired.html). 

I tried inserting the code above and below the org code but of no success.

Thanks.

**Comment by nxtruong** [comment] 2019-05-23 16:26
I'm not using scimax but vanilla Emacs and mu/mu4e. I have the same problem, but only for Apple's email apps. To be specific:
- If I read the email in gmail or Outlook, the attachment code is not shown and the attachments are included correctly.
- If I read the email in Apple's email apps (whether Mail.app on MacOS or Mail on iOS), the attachment code is shown and, most importantly, the attachments are nowhere to be found.

It's definitely because of `org-mu4e-compose-org-mode`. If I don't use that mode, everything works fine (attachment code not shown and attachments included correctly for Apple's mail apps). My current solution is to not use `org-mu4e-compose-org-mode` and whenever I need org-mode and HTML, I will selectively add org-mode text into the email's body and call `org-mime-htmlize` manually.

Note that `org-mu4e-compose-org-mode` is marked as DEPRECATED by its author, so perhaps it should not be used in its current state.

**Comment by jkitchin** [comment] 2019-05-29 17:05
Just to make sure I understand, this isn't a scimax issue right? I don't think it does anything related to =org-mu4e-compose-org-mode=.

**Comment by jkitchin** [comment] 2019-06-04 15:56
This doesn't seem to be a scimax issue, so I am closing it. If it is due to some setting in scimax, feel free to re-open it.

**Closed by jkitchin** 2019-06-04 15:56 UTC

**Comment by shrysr** [comment] 2020-02-24 01:18
For reference, the following reddit discussion references the same, and has some solutions. i.e use org-msg (which is quite interesting, but with caveats) or more practically, use mail-add-attachment instead. I'm currently experimenting with org-msg.
