### ISSUE TITLE
Org equation renumbering hack overestimates the equation numbers

### ISSUE THREAD

**Issue by abougouffa** [jkitchin/scimax#461] opened 2022-08-19 16:19 UTC
Hello,

I really liked the hack in `scimax-org-latex.el` which renumbers the equations previews in an Org document. 

However, the way it calculates the equation numbers in an `align` environment is subject to errors:

https://github.com/jkitchin/scimax/blob/451592d48cec973005b809474485735ccddb4e36/scimax-org-latex.el#L234-L245

It simply counts the `\\\\$` breaks to get the numbers, however, this is **not always true**. For example, in an equation with matrices like this:

```latex
\begin{align}
  \begin{bmatrix}
    A \\ % <-- it will count this one (when removing the comment)
    1
  \end{bmatrix}
  =&
  \begin{bmatrix}
    B & C \\ % <-- and this one
    D & 1
  \end{bmatrix}
  \begin{bmatrix}
    E & F \\ % <-- and this one
    0 & 1
  \end{bmatrix}
  \begin{bmatrix}
    G \\ 1
  \end{bmatrix}
  \\ =& % <-- I woldn't count this one, although is the right one to count
  \begin{bmatrix}
    H & I \\ % <-- and counts this one
    J & 1
  \end{bmatrix}
  \begin{bmatrix}
    K \\ 1
  \end{bmatrix}
\end{align}
```

The right way would be to somehow parse the `env` to count only the `\\` outside inner `\begin{something}` and `\end{somethinsg}` (`something` being `bmatrix` in the example).

**Comment by abougouffa** [comment] 2022-08-20 01:06
This is a dirty working PoC!

```elisp
(defun +parse-the-fun (str)
  "Parse the LaTeX environment STR.
Return an AST with newline/nonumber counts in each level."
  (let (ast)
    (with-temp-buffer
      (insert str)
      (goto-char (point-min))
      (while (re-search-forward
              (rx "\\"
                  (group (or "\\" "begin" "end" "nonumber"))
                  (zero-or-one "{" (group (* alnum)) "}"))
              nil t)
        (let ((cmd (match-string 1))
              (env (match-string 2)))
          (cond ((string= cmd "begin")
                 (push (list :env (intern env)) ast))
                ((string= cmd "\\")
                 (let ((curr (pop ast)))
                   (push (plist-put curr :newline (1+ (or (plist-get curr :newline) 0))) ast)))
                ((string= cmd "nonumber")
                 (let ((curr (pop ast)))
                   (push (plist-put curr :nonumber (1+ (or (plist-get curr :nonumber) 0))) ast)))
                ((string= cmd "end")
                 (let ((child (pop ast))
                       (parent (pop ast)))
                   (push (plist-put parent :childs (cons child (plist-get parent :childs))) ast)))))))
    (plist-get (car ast) :childs)))

(defun scimax-org-renumber-environment (orig-func &rest args)
  "A function to inject numbers in LaTeX fragment previews."
  (let ((results '())
        (counter -1))
    (setq results
          (cl-loop for (begin . env) in
                   (org-element-map (org-element-parse-buffer) 'latex-environment
                     (lambda (env)
                       (cons
                        (org-element-property :begin env)
                        (org-element-property :value env))))
                   collect
                   (cond
                    ((and (string-match "\\\\begin{equation}" env)
                          (not (string-match "\\\\tag{" env)))
                     (cl-incf counter)
                     (cons begin counter))
                    ((string-match "\\\\begin{align}" env)
                     (prog2
                         (cl-incf counter)
                         (cons begin counter)
                       (let ((p (car (+parse-the-fun env))))
                         ;; Parse the `env', count new lines in the align env as equations, unless
                         (cl-incf counter (- (or (plist-get p :newline) 0)
                                             (or (plist-get p :nonumber) 0))))))
                    (t
                     (cons begin nil)))))
    (when-let ((number (cdr (assoc (point) results))))
      (setf (car args)
            (concat
             (format "\\setcounter{equation}{%s}\n" number)
             (car args)))))
  (apply orig-func args))
```

**Comment by jkitchin** [comment] 2023-04-30 13:35
I don't see the problem with the existing code. With your example I get this output, which seems right?

<img width="445" alt="image" src="https://user-images.githubusercontent.com/1610070/235355606-4ca7f15a-88b7-452c-9a32-2439ca5b62c2.png">

**Comment by jkitchin** [comment] 2024-02-25 19:22
I can't reproduce the issue, so am closing this for now.

**Closed by jkitchin** 2024-02-25 19:22 UTC
