### ISSUE TITLE
sympy results are always converted to png

### ISSUE THREAD

**Issue by singletS** [jkitchin/scimax#39] opened 2017-02-14 16:09 UTC
Pounding on scimax's ob-ipython tweaks, I find that all results from sympy are getting converted into large pngs. This makes viewing output in emacs difficult and confuses the html exporter, which inserts the pngs instead of sympy's latex for mathjax rendering. (sympy's init_printing() allows the html exporter to work effectively with sympy latex output and mathjax.)

Using ob-ipython without scimax tweaks produces standard sympy output in results, so may be related to the mods in the ob-ipython-async-callback / mime-types?

The issue is reproducible on linux, emacs  26.0.50 using scimax or spacemacs:
```
Trying sympy in org.
#+BEGIN_SRC ipython :session :results output drawer
from sympy import *
# commenting out init_printing() results in no output
init_printing()
#+END_SRC

#+BEGIN_SRC ipython :session :results output drawer
3+2
#+END_SRC

#+BEGIN_SRC ipython :session :results output drawer
var('x y')
x**2 + y
#+END_SRC
```
(Found this simple problem after some wt? moments: I kept getting BIG result blocks with "nothing" in them.  Turns out my dark emacs theme was dutifully showing a large png with black text and a transparent (black) background...oof :)

Side question: I'm also getting a #+BEGIN_EXPORT latex block regardless of exporter; it's benign, but should this happen for only latex exports?

Thanks,
Steve

**Comment by jkitchin** [comment] 2017-02-14 16:30
I am not sure what a fix for this is. If you look at one of your cells, you can see that there is an image, and latex, and plain text output for the code 2+3 if you run it from a jupyter notebook.

```
{
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOBAMAAAAPuiubAAAAMFBMVEX///8AAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv3aB7AAAAD3RSTlMAzXYQMplU74mrIma7\nRN0SDTw+AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAATklEQVQIHWNgVGYJY2Bg//+/gYGBsVOLgYGB\nE4jh5G5VBwYGHgOuv2DBc2AyfgHDRAaG/gsMhQwM8QYMAQwMDxkYljJwVzEwcEVMNWAAADWrDnXF\n0pOGAAAAAElFTkSuQmCC\n",
      "text/latex": [
       "$$5$$"
      ],
      "text/plain": [
       "5"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "3+2"
   ]
  },
```

That is why you see all those things with my mods of ob-ipython. That is so you can export the org file to a notebook that looks almost like you created it from the notebook. The large image size is not so nice and is caused by org-mode rescaling it for some reason, but fixable with #+attr_org: :width if there is a way to determine what size it should be. I am not sure the best way to do that off the top of my head.

I am not sure what you mean by #+BEGIN_EXPORT latex block regardless of exporter. Any non-latex exporter should just ignore that. I can see that wanting mathjax in html would be nice, but I don't know how you would get that. Maybe if instead of a Latex cell, it was a markdown cell that would work, but you can output more than math in a latex cell, so it would not always work. You would probably still get the image though. There isn't a way to specify a precedence right now or an obvious way to do it either.

Maybe a set of file directives could control this behavior. Any ideas?

**Comment by singletS** [comment] 2017-02-14 19:25
Ok, I didn't realize that jupyter spits out all the mime types...thanks for helping me understand.  Right, BEGIN_EXPORTS_latex aren't a problem; I had just never seen them automatically appearing before.

Yes, identifying which mime type gets processed (or at least has precedence) would be helpful. By uncommenting the text/plain lines in scimax-org-babel-ipython, I can get html files that mathjax renders. I suspect this only occurs for python modules that emit multiple forms for jupyter (like sympy) but who knows what will come with extensions...

If a file directive or variable is feasible, something like this?
```ob-ipython-results-(type|form|output): plain image latex nil```
```ob-ipython-mimetypes: ```
By default or if nil, return results for all mime/type that scimax recognizes?
I'm fine with either directives or variables...whatever is easiest for the maintainer :)

FWIW, here's my naive method for getting unmodified ob-ipython, sympy, and html exporter to produce html that's rendered with mathjax (here, ":results output" gives blank blocks, but :results verbatim works. Hmm.)  I've also used a simple elisp function and :post to wrap results with \\[ \\] but this was clunky compared to the sympy printer.
```
Using sympy in org mode.

#+BEGIN_SRC ipython :session :results verbatim drawer
from sympy import *
init_printing()
#+END_SRC

#+RESULTS:
:RESULTS:
:END:

#+BEGIN_SRC ipython :session :results verbatim drawer :exports none
def myprinter(s):
    return "\[ " + latex(s) + " \]"
init_printing(pretty_printer=myprinter)
#+END_SRC

#+RESULTS:
:RESULTS:
:END:

#+BEGIN_SRC ipython :session :results verbatim drawer :exports both
var('x y')
sqrt(x**2 + y)
#+END_SRC

#+RESULTS:
:RESULTS:
\[ \sqrt{x^{2} + y} \]
:END:
```
If you have other ideas for html export tricks...

**Comment by jkitchin** [comment] 2017-05-23 16:23
I have pushed some code to address this.

You can do this to get:
#+BEGIN_SRC ipython :session :results verbatim drawer :exports both :ob-ipython-results text/latex
var('x y')
sqrt(x**2 + y)
#+END_SRC

to get the latex output. you can also specify text/plain, or image/png.

**Comment by singletS** [comment] 2017-05-25 15:38
Nice...thanks!

I'm seeing one minor glitch; `:output verbatim drawer`, needs a newline before the `BEGIN_EXPORT` block.  Using `:output results drawer` gives the newline.
```
#+BEGIN_SRC ipython :session :results verbatim drawer :ob-ipython-results text/latex
from sympy import *
init_printing()
var('x y z')
f = sin(x**2 + y * sqrt(z))
f.diff(x)
#+END_SRC

#+RESULTS:
:RESULTS:
       ⎛ 2       ⎞
2⋅x⋅cos⎝x  + y⋅√z⎠#+BEGIN_EXPORT latex
$$2 x \cos{\left (x^{2} + y \sqrt{z} \right )}$$
#+END_EXPORT
:END:
```
A quick pandas test for html and png.
```
#+BEGIN_SRC ipython :session :output verbatim drawer :ob-ipython-results text/html
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.DataFrame(np.random.randn(6,4),index=pd.date_range('1/1/2000',periods=6, freq='1h'))
df
#+END_SRC

#+RESULTS:
:RESULTS:
                            0         1         2         3
2000-01-01 00:00:00 -0.132572 -0.610363  1.619654  0.092325
2000-01-01 01:00:00  0.888098  1.140540 -1.508990  1.262268
2000-01-01 02:00:00  2.312697 -1.400131  1.379136 -0.707619
2000-01-01 03:00:00 -0.360600  0.148460 -0.956910  0.747633
2000-01-01 04:00:00 -0.170983 -0.134935 -0.803080  0.381069
2000-01-01 05:00:00 -0.577339  0.147913  0.145546 -0.997263#+BEGIN_EXPORT HTML
<div>
<style>

[snip]
</div>
#+END_EXPORT
:END:
 
#+BEGIN_SRC ipython :session :results verbatim drawer :ob-ipython-result text/png
df.plot(subplots=True, layout=(2,2), figsize=(10,10));
#+END_SRC
```

**Comment by jkitchin** [comment] 2017-05-25 17:56
Thanks, I have pushed a small fix that addresses these issues. I never use value for results so I hadn't seen them ;)

**Closed** 2017-05-25 19:43 UTC
