### ISSUE TITLE
ox-ipynb generates Markdown blocks with a null source

### ISSUE THREAD

**Issue by xelibrion** [jkitchin/scimax#44] opened 2017-03-09 09:36 UTC
Hi John,

I've noticed this behaviour a little while ago and not sure if you had experienced any of this. 
Basically, if there's no text after the last src block in an org file, exporter generates a Markdown cell
with the following content
```
{ "cell_type": "markdown", "metadata": {}, "source": [null] }
```

The problem is that `[null]` is not considered valid structure by Jupyter and it does not allow to open the notebook, where `[""]` does work.

Here's the sample org file that might help you to reproduce the problem: 
```
#+BEGIN_SRC ipython
print "Hello"
#+END_SRC
```

**Comment by jkitchin** [comment] 2017-03-09 15:37
I can't reproduce this issue. It might be because require-final-newline is set to t. I can't figure out where that happens though. I did fix another issue that has been bugging me though which is when there are empty results.

**Comment by xelibrion** [comment] 2017-03-10 00:40
My configuration has `require-final-newline` set to `t` as well, but the issue is occurring. I believe it might be related to the difference in org-mode versions.

**Comment by jkitchin** [comment] 2017-05-10 01:50
Closing this until it is more clear what causes it. in org9 I cannot reproduce it.

**Closed by jkitchin** 2017-05-10 01:50 UTC
