### ISSUE TITLE
Problems with sorting

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#433] opened 2021-11-07 09:11 UTC
The included file used to work, but stops with 8920ccd.

I get the following error:

```
(data '(("asd" 30 "30 €") ("sdf" 80 "80 €") ("fgh" 15 "15 €") ("dfg" 50 "50 €") ("GHz" 143 "143 €") ("hjk" 60 "60 €")))

org-babel-insert-result: Wrong type argument: markerp, nil
```

This commit changed `org-ref` to version 3.

(For the next time I'll learn how to use `git bisect` instead of doing it with pencil and paper.)

[ECM2.txt](https://github.com/jkitchin/scimax/files/7491983/ECM2.txt)

**Comment by jkitchin** [comment] 2021-11-07 14:11
I can't reproduce your example, it works fine for me. I have seen some issues like you describe but only in a scenario where I am exporting from a src block.

I can't think of any reason the commit you reference could do anything to change this. It doesn't change anything in scimax besides org-ref as far as I can see. If it was responsible, I would think commenting out the use-package org-ref line in packages.el would make your file work again.

Can you share the whole contents of *Backtrace* when you see the error?

**Comment by AKielhorn** [comment] 2021-11-07 16:15
When I comment `org-ref` it works.
I get 

```
Error (use-package): scimax-org/:init: Cannot open load file: No such file or directory, org-ref
Error (use-package): scimax-journal/:catch: Cannot open load file: No such file or directory, org-ref
```

but that was expected.

I removed my `user.el` but that didn't change anything.

After [bd]isecting `custom.el`, I discovered the culprit:

```
'(org-export-backends '(ascii beamer html icalendar latex md odt))
```

> Can you share the whole contents of Backtrace when you see the error?

If you tell me how to get it, I will.

**Comment by jkitchin** [comment] 2021-11-07 16:21
there should be a buffer called *Backtrace*, it is the contents of that buffer.

I don't understand how that culprit line could influence that error. or how org-ref could interact with it. weird.

org-ref does define an export backend, but I can't see how it could cause that issue.

**Comment by AKielhorn** [comment] 2021-11-08 06:29
I don't have a buffer `*Backtrace`.

Do I have to enable anything to get it?

**Comment by AKielhorn** [comment] 2021-11-08 13:09
Please find included the backtrace.

But you probably won't need it anymore:

In `org-ref` you derive a backend from `org`.
In my `custom.el` I don't include `org` as a backend.

See second backtrace which happened when I reload `org` uncompiled.

Once I include it, the problem is gone.

With this information you should be able to fix this.

Thanks for walking me through the backtrace.

**Comment by jkitchin** [comment] 2021-11-08 15:12
huh. that is weird. I don't see the backtraces, (maybe they weren't attached?), but I see what is happening I think. 

I don't understand why this has anything to do with executing the src blocks though. in org-ref-export.el, there is `(require 'ox-org)`, which I thought should be ok.

**Comment by AKielhorn** [comment] 2021-11-08 16:32
Second try to attache them:

[ECM2-bt.txt](https://github.com/jkitchin/scimax/files/7498520/ECM2-bt.txt)

**Comment by jkitchin** [comment] 2021-11-08 18:53
Thanks. I can see these. I don't understand what the issue is though. I would have thought that `(require 'ox-org)` would cover the exporter, and don't understand why it doesn't. It also seems unrelated to the error with uncompiled org.  The only thing I have been able to see is with this block which is derived from the top error. 

```
#+BEGIN_SRC emacs-lisp 
(org-babel-insert-result
 '(("Hersteller" "Preis" "Preis")
   hline
   ("fgh" 15 "15 €")
   ("asd" 30 "30 €")
   ("dfg" 50 "50 €")
   ("hjk" 60 "60 €")
   ("sdf" 80 "80 €")
   ("GHz" 143 "143 €"))
 '("replace")
 '("emacs-lisp" "(sort data (lambda (row1 row2) (< (nth 1 row1) (nt..."
   ((:var data ("asd" 30 "30 €") ("sdf" 80 "80 €") ("fgh" 15 "15 €")
	  ("dfg" 50 "50 €") ("GHz" 143 "143 €") ("hjk" 60 "60 €"))
    (:colname-names (data "Hersteller" "Preis" "Preis"))
    (:rowname-names) (:result-params "replace")
    (:result-type . value)
    (:results . "replace")
    (:exports . "results")
    (:session . "none")
    (:cache . "no")
    (:noweb . "no")
    (:hlines . "no")
    (:tangle . "no")
    (:lexical . "no")
    (:colnames . "t"))
   "" "resortedp" 284 "(ref:%s)")
 nil "emacs-lisp")
#+END_SRC
```

If you put that in an org-file, and C-cC-c it, I get 

```
#+RESULTS:
: Code block evaluation complete.
```

with no error. If you put your cursor at the closing ) and type C-x C-e, then you see this:

```
#+RESULTS:
| Hersteller | Preis | Preis |
|------------+-------+-------|
| fgh        |    15 | 15 €  |
| asd        |    30 | 30 €  |
| dfg        |    50 | 50 €  |
| hjk        |    60 | 60 €  |
| sdf        |    80 | 80 €  |
| GHz        |   143 | 143 € |

```

still no error. But, if you type C-c ' to do a special edit, and then do that same thing then I see:

`org-babel-insert-result: Wrong type argument: markerp, nil`

which makes me think somehow the result is trying to get inserted into the wrong buffer. I am still not sure how that might be happening. 

What do you have `org-export-before-parsing-hook` set to?

C-h v org-export-before-parsing-hook

**Comment by AKielhorn** [comment] 2021-11-09 06:14
It is set to `nil`.

**Comment by jkitchin** [comment] 2021-11-09 16:11
hm. I don't know what else to look at. I can't reproduce this with a vanilla emacs and org-ref installation.

**Comment by AKielhorn** [comment] 2021-11-10 05:28
Maybe we should close this issue and open a new one:

```
Export error: org-babel-insert-result: Wrong type argument: markerp, nil
```

Where we explain that `org` needs to be in:
```
'(org-export-backends '(org))
```

when this option is set via `customize` or an `init.el` file.

That will lead users who encounter this problem in the future to the right answer.

**Closed** 2023-04-27 14:01 UTC
