### ISSUE TITLE
org-latex-compile: Wrong type argument: listp, ox-manuscript-latex-pdf-process

### ISSUE THREAD

**Issue by AKielhorn** [jkitchin/scimax#469] opened 2023-02-10 06:07 UTC
Hello!

Since a recent org update I get the following message

`
org-latex-compile: Wrong type argument: listp, ox-manuscript-latex-pdf-process
`

The TeX file is generated, but no TeX -> pdf process (pdflatex in my case) is started.

I'm using
`
Org mode version 9.6.1 (release_9.6.1-211-gaa48c8 @ /Users/axel/src/Emacs/org-mode/lisp/)
GNU Emacs 28.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2022-09-12
`
This was working fine last year.

Edit:

It works fine if I comment the line:
`
(setq org-latex-pdf-process 'ox-manuscript-latex-pdf-process)
`

in ox-manusrcipt.el

Greetings
Axel

**Comment by jkitchin** [comment] 2023-02-11 14:39
What does the help for `org-latex-pdf-process` say? In my org, this variable can be a list of strings or a function.

**Comment by AKielhorn** [comment] 2023-02-12 07:55
```
(defcustom org-latex-pdf-process
  (if (executable-find "latexmk")
      '("latexmk -f -pdf -%latex -interaction=nonstopmode -output-directory=%o %f")
    '("%latex -interaction nonstopmode -output-directory %o %f"
      "%latex -interaction nonstopmode -output-directory %o %f"
      "%latex -interaction nonstopmode -output-directory %o %f"))
  "Commands to process a LaTeX file to a PDF file.
```

> The command output will be parsed to extract compilation errors and
> warnings according to `org-latex-known-warnings'.
> 
> This is a list of strings, each of them will be given to the
> shell as a command.  %f in the command will be replaced by the
> relative file name, %F by the absolute file name, %b by the file
> base name (i.e. without directory and extension parts), %o by the
> base directory of the file, %O by the absolute file name of the
> output file, %latex is the LaTeX compiler (see
> `org-latex-compiler'), and %bib is the BibTeX-like compiler (see
> `org-latex-bib-compiler').
> 
> The reason why this is a list is that it usually takes several
> runs of `pdflatex', maybe mixed with a call to `bibtex'.  Org
> does not have a clever mechanism to detect which of these
> commands have to be run to get to a stable result, and it also
> does not do any error checking.
> 
> Consider a smart LaTeX compiler such as `texi2dvi' or `latexmk',
> which calls the \"correct\" combinations of auxiliary programs.
> 
> Alternatively, this may be a Lisp function that does the
> processing, so you could use this to apply the machinery of
> AUCTeX or the Emacs LaTeX mode.  This function should accept the
> file name as its single argument."

Later there is:

```
(process (if (functionp org-latex-pdf-process) org-latex-pdf-process
                    ;; Replace "%latex" with "%L" and "%bib" and
                    ;; "%bibtex" with "%B" to adhere to `format-spec'                
                    ;; specifications.
                    (mapcar (lambda (command)
                              (replace-regexp-in-string
                               "%\\(?:\\(?:bib\\|la\\)tex\\|bib\\)\\>"                          
                               (lambda (m) (upcase (substring m 0 2)))                          
                               command))
                            org-latex-pdf-process)))
```

I don't see any recent change.

**Comment by jkitchin** [comment] 2023-02-12 14:25
you probably need a more detailed traceback to see what the issue is. ox-manuscript-latex-pdf-process is an interactive Lisp function in `ox-manuscript.el', so it should be fine for org-latex-pdf-process to be set to that. You certainly don't need to sety org-latex-pdf-process to that function though.

**Comment by AKielhorn** [comment] 2023-02-16 18:43
I disabled `ox-manuscript-latex-pdf-process` and switched to `latexmk` as my pdf engine. This does everything I need right now.

You can consider this issue closed.

**Comment by jkitchin** [comment] 2023-02-17 17:30
ok. I can't reproduce it yet. I will close this for now.

**Closed by jkitchin** 2023-02-17 17:30 UTC
